site_name: Makerspace des Repair-Café Hilpoldstein
site_url: https://makes-hacks-hip.github.io
nav:
    - Repair-Café: https://www.repaircafe-hilpoltstein.de
    - Makerspace: https://makes-hacks-hip.de
theme: readthedocs
