site_name: Makerspace des Repair-Café Hilpoldstein
site_url: https://makes-hacks-hip.github.io
nav:
    - Repair-Café: https://www.repaircafe-hilpoltstein.de
    - Makerspace: https://makes-hacks-hip.de
    - Lötstation: https://makes-hacks-hip.github.io/MakeLoetstation/
    - Feinstaubsensor: https://makes-hacks-hip.github.io/Feinstaubsensor/
    - Github Guide: github.md
theme: readthedocs
repo_url: https://github.com/makes-hacks-hip/makes-hacks-hip.github.io/
edit_uri: edit/main/docs/
