site_name: Makerspace Hilpoltstein
site_url: https://makes-hacks-hip.github.io
nav:
    - 'Makerspace des Repair-Café':
        - Makerspace: https://makes-hacks-hip.de
        - Repair-Café: https://www.repaircafe-hilpoltstein.de
    - 'Projekte':
        - Lötstation: https://makes-hacks-hip.github.io/MakeLoetstation/
        - Feinstaubsensor: https://makes-hacks-hip.github.io/Feinstaubsensor/
        - LoRaWan Gateway: https://makes-hacks-hip.github.io/LoRaWanGateway/
    - 'Lernprojekte':
        - Micro:bit: https://makes-hacks-hip.github.io/microbit/
    - 'Guides':
        - Github Guide: github.md
        - Komponenten Guide: komponenten.md
theme: readthedocs
repo_url: https://github.com/makes-hacks-hip/makes-hacks-hip.github.io/
edit_uri: edit/main/docs/
